### ISSUE TITLE
Initiation

### ISSUE THREAD

**Issue by fasade-tech** [Adam-Hammo/arlulaapi#1]
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 6
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information
>>> import arlulaapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
arlulavenv\lib\site-packages\arlulaapi\__init__.py", line 1, in <module
    import grequests
ModuleNotFoundError: No module named 'grequests'
>>> import arlulaapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
arlulavenv\lib\site-packages\arlulaapi\__init__.py", line 1, in <module
    import grequests
**ModuleNotFoundError: No module named 'grequests'**

**Comment by Adam-Hammo** [comment]
Hopefully resolved, package dependencies were not being picked up by setup.py.
