### ISSUE TITLE
API Error checking Authorisation not working

### ISSUE THREAD

**Issue by mayurpande** [Adam-Hammo/arlulaapi#2]
I cannot seem to authenticate. I have followed the example like so;

```
import arlulaapi

arlula_session = arlulaapi.ArlulaSession(<my_api_name>, <my_api_key>)
```
However I still get the `arlulaapi.ArlulaSessionError: Error checking Authorisation`

**Comment by Adam-Hammo** [comment]
Hi @mayurpande, this could be a few things. Are you able to confirm that your credentials work correctly outside of the package (i.e. calling the Arlula API directly)?
Also, I see that above you've written <name>, <key> - can you confirm that you're actually passing <key>,<secret> into the ArlulaSession()?
Finally, could you please check that you're passing in the key and secret as unencoded plaintext - the package will encode the values according to the HTTP Basic Auth Mechanism.

**Comment by Adam-Hammo** [comment]
Hi @mayurpande, do you have any update on the above?

**Comment by mayurpande** [comment]
Thanks, I actually did not need to use it in the end.
